[[edge]]
from = "br-4221"
to = "br-7678"
kind = "blocks"
created_at = "2026-09-28T16:42:03.765Z"

[[edge]]
from = "br-4221"
to = "br-55e2"
kind = "blocks"
created_at = "2026-09-28T17:06:48.604Z"

[[edge]]
from = "br-1dfe"
to = "br-37ed"
kind = "blocks"
created_at = "2026-09-28T18:08:05.296Z"

[[edge]]
from = "br-1271"
to = "br-ab22"
kind = "blocks"
created_at = "2026-09-28T22:30:10.148Z"

[[edge]]
from = "br-ab22"
to = "br-2450"
kind = "blocks"
created_at = "2026-09-28T22:30:10.163Z"

[[edge]]
from = "br-ae60"
to = "br-e531"
kind = "blocks"
created_at = "2026-09-29T03:21:37.794Z"

[[edge]]
from = "br-ae60"
to = "br-41e1"
kind = "blocks"
created_at = "2026-09-29T03:21:38.187Z"

[[edge]]
from = "br-ae60"
to = "br-3058"
kind = "blocks"
created_at = "2026-09-29T03:21:38.579Z"

[[edge]]
from = "br-9821"
to = "br-3584"
kind = "blocks"
created_at = "2026-09-29T05:50:58.724Z"

[[edge]]
from = "br-3584"
to = "br-6774"
kind = "blocks"
created_at = "2026-09-29T05:50:58.737Z"

[[edge]]
from = "br-3584"
to = "br-66e2"
kind = "blocks"
created_at = "2026-09-29T05:50:58.751Z"

[[edge]]
from = "br-07d6"
to = "br-66e2"
kind = "blocks"
created_at = "2026-09-29T05:50:58.765Z"

[[edge]]
from = "br-d226"
to = "br-dd44"
kind = "blocks"
created_at = "2026-09-29T05:50:58.778Z"

[[edge]]
from = "br-930e"
to = "br-cc25"
kind = "blocks"
created_at = "2026-09-29T08:10:47.913Z"

[[edge]]
from = "br-6dd6"
to = "br-5d2a"
kind = "blocks"
created_at = "2026-09-29T08:10:47.926Z"
