[[edge]]
from = "br-4221"
to = "br-7678"
kind = "blocks"
created_at = "2026-09-28T16:42:03.765Z"

[[edge]]
from = "br-4221"
to = "br-55e2"
kind = "blocks"
created_at = "2026-09-28T17:06:48.604Z"

[[edge]]
from = "br-1dfe"
to = "br-37ed"
kind = "blocks"
created_at = "2026-09-28T18:08:05.296Z"

[[edge]]
from = "br-1271"
to = "br-ab22"
kind = "blocks"
created_at = "2026-09-28T22:30:10.148Z"

[[edge]]
from = "br-ab22"
to = "br-2450"
kind = "blocks"
created_at = "2026-09-28T22:30:10.163Z"
