[[tier]]
tasks = [
    "br-ce1a",
    "br-f025",
]

[[tier]]
tasks = [
    "br-0b22",
    "br-f86f",
    "br-9474",
    "br-f4d1",
]

[[tier]]
tasks = [
    "br-7d81",
    "br-0589",
]

[[tier]]
tasks = ["br-b29c"]
