[[tier]]
tasks = [
    "br-0838",
    "br-1dfe",
]

[[tier]]
tasks = [
    "br-bc21",
    "br-00eb",
]

[[tier]]
tasks = ["br-a702"]

[[tier]]
tasks = [
    "br-e8b3",
    "br-d5c8",
    "br-0e14",
    "br-7ab7",
    "br-37ed",
    "br-7678",
    "br-55e2",
]

[[tier]]
tasks = [
    "br-7bf8",
    "br-3822",
    "br-f6ad",
]
