[[tier]]
tasks = [
    "br-88d4",
    "br-6b8a",
    "br-2718",
]

[[tier]]
tasks = [
    "br-ba9e",
    "br-7e5a",
    "br-afda",
]

[[tier]]
tasks = [
    "br-e7e2",
    "br-751e",
    "br-8b98",
]

[[tier]]
tasks = ["br-79c3"]

[[tier]]
tasks = ["br-14cd"]
