# Generated by `bridle spec export` from the capability spec. Edit the spec, never this file.

Feature: widgets

  Rule: Widgets are counted

    @smoke @s-b310
    Scenario: Counting two widgets
      Given two widgets
      When they are counted
      Then the count is 2

  Rule: Widgets have colours

    @s-b312
    Scenario Outline: Colouring
      When a widget is coloured <colour>
      Then it reports <colour>

      Examples:
        | colour |
        | red |
        | blue |
