//! `bridle spec export`: the parsed specs as Gherkin or JSON, for test runners
//! (docs/design/specs-to-tests.md). Nothing here is committed; runners
//! regenerate it at collection time.

use std::path::Path;

use bridle_spec::{Keyword, Requirement, Scenario, Spec, Verification};
use serde::Serialize;

/// Bump when a JSON field is renamed or removed (adding fields doesn't).
pub const JSON_VERSION: u32 = 1;

/// The capability name: the file stem, or the directory name for an OpenSpec
/// `<capability>/spec.md`.
pub fn capability(path: &Path) -> String {
    let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("spec");
    if stem == "spec"
        && let Some(dir) = path
            .parent()
            .and_then(Path::file_name)
            .and_then(|s| s.to_str())
    {
        return dir.to_string();
    }
    stem.to_string()
}

/// One `.feature`: a Rule per requirement, a Scenario per executable
/// scenario. A requirement with none still appears as a bare Rule, so the gap
/// is visible (as in data-contracts' tools/spec-to-feature.py).
pub fn gherkin(capability: &str, spec: &Spec) -> String {
    let mut out = format!(
        "# Generated by `bridle spec export` from the capability spec. Edit the spec, never this file.\n\nFeature: {capability}\n\n"
    );
    for req in &spec.requirements {
        out.push_str(&format!("  Rule: {}\n\n", req.title));
        for s in req
            .scenarios
            .iter()
            .filter(|s| s.verification == Verification::Executable)
        {
            scenario(&mut out, s);
        }
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

/// The Gherkin spelling of a step keyword.
fn keyword(k: Keyword) -> &'static str {
    match k {
        Keyword::Given => "Given",
        Keyword::When => "When",
        Keyword::Then => "Then",
        Keyword::And => "And",
        Keyword::But => "But",
    }
}

fn scenario(out: &mut String, s: &Scenario) {
    let tags: Vec<String> = s
        .tags
        .iter()
        .cloned()
        .chain(s.id.iter().cloned())
        .map(|t| format!("@{t}"))
        .collect();
    if !tags.is_empty() {
        out.push_str(&format!("    {}\n", tags.join(" ")));
    }
    let kind = if s.examples.is_some() {
        "Scenario Outline"
    } else {
        "Scenario"
    };
    out.push_str(&format!("    {kind}: {}\n", s.title));
    if !s.description.is_empty() {
        for line in s.description.lines() {
            out.push_str(&format!("      {line}\n"));
        }
        out.push('\n');
    }
    for step in &s.steps {
        out.push_str(&format!("      {} {}\n", keyword(step.keyword), step.text));
    }
    if let Some(ex) = &s.examples {
        out.push_str("\n      Examples:\n");
        out.push_str(&format!("        | {} |\n", ex.header.join(" | ")));
        for row in &ex.rows {
            out.push_str(&format!("        | {} |\n", row.join(" | ")));
        }
    }
    out.push('\n');
}

/// The `--format json` document. Field names are the contract: see
/// docs/design/specs-to-tests.md.
#[derive(Serialize)]
pub struct JsonExport {
    pub version: u32,
    pub specs: Vec<JsonSpec>,
}

#[derive(Serialize)]
pub struct JsonSpec {
    pub file: String,
    pub capability: String,
    pub title: Option<String>,
    pub requirements: Vec<JsonRequirement>,
}

#[derive(Serialize)]
pub struct JsonRequirement {
    pub id: Option<String>,
    pub title: String,
    pub protected: bool,
    pub traces: Vec<JsonTrace>,
    pub text: String,
    pub line: usize,
    pub scenarios: Vec<JsonScenario>,
}

#[derive(Serialize)]
pub struct JsonTrace {
    pub target: String,
    pub hash: String,
}

#[derive(Serialize)]
pub struct JsonScenario {
    pub id: Option<String>,
    pub title: String,
    pub line: usize,
    pub executable: bool,
    pub tags: Vec<String>,
    pub description: String,
    pub steps: Vec<JsonStep>,
    pub examples: Option<JsonExamples>,
}

#[derive(Serialize)]
pub struct JsonStep {
    /// `Given`, `When`, `Then`, `And` or `But`.
    pub keyword: &'static str,
    pub text: String,
    pub line: usize,
}

#[derive(Serialize)]
pub struct JsonExamples {
    pub header: Vec<String>,
    pub rows: Vec<Vec<String>>,
}

pub fn json_spec(file: &Path, spec: &Spec) -> JsonSpec {
    JsonSpec {
        file: file.display().to_string(),
        capability: capability(file),
        title: spec.title.clone(),
        requirements: spec.requirements.iter().map(json_requirement).collect(),
    }
}

fn json_requirement(r: &Requirement) -> JsonRequirement {
    JsonRequirement {
        id: r.id.clone(),
        title: r.title.clone(),
        protected: r.protected,
        traces: r
            .traces
            .iter()
            .map(|t| JsonTrace {
                target: t.target.clone(),
                hash: t.hash.clone(),
            })
            .collect(),
        text: r.text.clone(),
        line: r.line,
        scenarios: r.scenarios.iter().map(json_scenario).collect(),
    }
}

fn json_scenario(s: &Scenario) -> JsonScenario {
    JsonScenario {
        id: s.id.clone(),
        title: s.title.clone(),
        line: s.line,
        executable: s.verification == Verification::Executable,
        tags: s.tags.clone(),
        description: s.description.clone(),
        steps: s
            .steps
            .iter()
            .map(|st| JsonStep {
                keyword: keyword(st.keyword),
                text: st.text.clone(),
                line: st.line,
            })
            .collect(),
        examples: s.examples.as_ref().map(|e| JsonExamples {
            header: e.header.clone(),
            rows: e.rows.clone(),
        }),
    }
}
